#!/usr/bin/env bash
# Persist a gogh theme so it survives new terminal windows / restarts.
#
# Usage: persist.sh /path/to/theme.sh <terminal>
#        persist.sh --terminal <name>   # update last_active only (sync / tmux-start)
set -u

_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=state.sh disable=SC1091
source "$_dir/state.sh"

case "${1:-}" in
  --terminal)
    gogh_state_write_last_active "${2:-}"
    exit 0
    ;;
esac

file="${1:-}"
term="${2:-}"
[ -f "$file" ] || exit 0

# Parse "#RRGGBB" from theme export without sourcing the script.
field() {
  sed -n "s/^export $1=\"\(#[0-9A-Fa-f]\{6\}\)\".*/\1/p" "$file" | head -n1
}

name=$(sed -n 's/^export PROFILE_NAME="\([^"]*\)".*/\1/p' "$file" | head -n1)
[ -z "$name" ] && name=$(basename "$file" .sh)

gogh_state_write_theme "$term" "$name" "$(basename "$file")"

# WezTerm: write colors.lua; config reload applies palette to all panes (no OSC).
case "$term" in
  wezterm)
    cfg="${WEZTERM_CONFIG_DIR:-$HOME/.config/wezterm}"
    mkdir -p "$cfg"
    out="$cfg/colors.lua"
    cursor=$(field CURSOR_COLOR)
    {
      echo "-- Generated by the colorscheme() shell function — do not edit by hand."
      echo "-- Source theme: $(basename "$file")"
      echo "return {"
      echo "  foreground = \"$(field FOREGROUND_COLOR)\","
      echo "  background = \"$(field BACKGROUND_COLOR)\","
      if [ -n "$cursor" ]; then
        echo "  cursor_bg = \"$cursor\","
        echo "  cursor_border = \"$cursor\","
      fi
      echo "  ansi = {"
      for i in 01 02 03 04 05 06 07 08; do echo "    \"$(field "COLOR_$i")\","; done
      echo "  },"
      echo "  brights = {"
      for i in 09 10 11 12 13 14 15 16; do echo "    \"$(field "COLOR_$i")\","; done
      echo "  },"
      echo "}"
    } >"$out"
    ;;
  *)
    # kitty / alacritty: gogh already writes their config files.
    :
    ;;
esac
