#!/usr/bin/env bash
# uninstall.sh — detach this machine from terminal-config.
#
# By default runs non-interactively and assumes yes for every step (backups are
# always created before removal). Pass -i or --interactive to confirm each step.
#
# Does NOT remove brew packages, ~/.nvm, ~/.fzf, Gogh clones, TPM, etc.

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$DOTFILES_DIR/lib/helpers.sh"

CONFIRM_INTERACTIVE=false

for arg in "$@"; do
  case "$arg" in
    -i|--interactive) CONFIRM_INTERACTIVE=true ;;
    -h|--help)
      echo "Usage: $0 [-i|--interactive]"
      echo ""
      echo "  -i, --interactive   Ask before each step (default: yes to all)"
      echo "  -h, --help          Show this help"
      exit 0
      ;;
    *)
      echo -e "${YELLOW}Unknown option:${RESET} $arg (try --help)"
      exit 1
      ;;
  esac
done

echo -e "${CYAN}${BOLD}━━━  Uninstalling dotfiles  ━━━${RESET}"
if [[ "$CONFIRM_INTERACTIVE" == true ]]; then
  echo -e "${DIM}Interactive mode — you will be asked before each step.${RESET}"
else
  echo -e "${DIM}Non-interactive mode — assuming yes (use -i to confirm each step).${RESET}"
fi
echo ""

# ── Shell RC symlinks ─────────────────────────────────────────────────────────
if confirm_yes "Remove shell RC symlinks (~/.zshrc, ~/.bashrc) pointing into this repo?"; then
  echo -e "${BOLD}→ Shell RC${RESET}"
  uninstall_symlink_if_mine "$DOTFILES_DIR" "${HOME}/.zshrc"
  uninstall_symlink_if_mine "$DOTFILES_DIR" "${HOME}/.bashrc"
  echo ""
fi

# ── tmux ──────────────────────────────────────────────────────────────────────
if confirm_yes "Remove ~/.tmux.conf (backup to ~/.tmux.conf.uninstall.old)?"; then
  echo -e "${BOLD}→ tmux${RESET}"
  uninstall_copied_config "$DOTFILES_DIR" "${HOME}/.tmux.conf"
  echo ""
fi

# ── Terminal emulators ────────────────────────────────────────────────────────
if confirm_yes "Remove terminal emulator configs from ~/.config/ (with backup)?"; then
  echo -e "${BOLD}→ Terminal emulators${RESET}"
  uninstall_copied_config "$DOTFILES_DIR" "${HOME}/.config/alacritty/alacritty.yml"
  uninstall_copied_config "$DOTFILES_DIR" "${HOME}/.config/kitty/kitty.conf"
  uninstall_copied_config "$DOTFILES_DIR" "${HOME}/.config/wezterm/wezterm.lua"
  echo ""
fi

if confirm_yes "Remove ~/.config/wezterm/colors.lua (generated by colorscheme)?"; then
  echo -e "${BOLD}→ WezTerm theme${RESET}"
  uninstall_copied_config "$DOTFILES_DIR" "${HOME}/.config/wezterm/colors.lua"
  echo ""
fi

# ── Optional empty bash_aliases ───────────────────────────────────────────────
if [ -f "${HOME}/.bash_aliases" ] && [ ! -s "${HOME}/.bash_aliases" ] && [ ! -L "${HOME}/.bash_aliases" ]; then
  if confirm_yes "Remove empty ~/.bash_aliases created by install?"; then
    echo -e "${BOLD}→ bash_aliases${RESET}"
    rm "${HOME}/.bash_aliases"
    echo -e "  ${GREEN}✓${RESET}  Removed empty ~/.bash_aliases"
    echo ""
  fi
fi

echo -e "${GREEN}${BOLD}Done!${RESET}"
echo ""
echo -e "  ${DIM}The repo at ${DOTFILES_DIR} was not deleted.${RESET}"
echo -e "  ${DIM}Tools installed by bootstrap (tmux, nvm, fzf, Gogh, TPM, etc.) were not removed.${RESET}"
echo -e "  ${DIM}Personal files in the repo (e.g. shell/custom.sh) were not touched.${RESET}"
echo ""
echo -e "  Open a new shell to pick up the changes."
