#!/usr/bin/env bash
# Persist a gogh theme so it survives new terminal windows / restarts.
#
# Gogh applies WezTerm themes only via live escape sequences (session-only).
# This writes the theme's colours to a machine-local file that wezterm.lua
# loads, so the scheme sticks. WezTerm auto-reloads when this file changes.
#
# Usage: gogh-persist.sh /path/to/theme.sh <terminal>
set -u

file="${1:-}"
term="${2:-}"
[ -f "$file" ] || exit 0

field() {
  sed -n "s/^export $1=\"\(#[0-9A-Fa-f]\{6\}\)\".*/\1/p" "$file" | head -n1
}

case "$term" in
  wezterm)
    cfg="${WEZTERM_CONFIG_DIR:-$HOME/.config/wezterm}"
    mkdir -p "$cfg"
    out="$cfg/colors.lua"
    cursor=$(field CURSOR_COLOR)
    {
      echo "-- Generated by the colorscheme() shell function — do not edit by hand."
      echo "-- Source theme: $(basename "$file")"
      echo "return {"
      echo "  foreground = \"$(field FOREGROUND_COLOR)\","
      echo "  background = \"$(field BACKGROUND_COLOR)\","
      if [ -n "$cursor" ]; then
        echo "  cursor_bg = \"$cursor\","
        echo "  cursor_border = \"$cursor\","
      fi
      echo "  ansi = {"
      for i in 01 02 03 04 05 06 07 08; do echo "    \"$(field "COLOR_$i")\","; done
      echo "  },"
      echo "  brights = {"
      for i in 09 10 11 12 13 14 15 16; do echo "    \"$(field "COLOR_$i")\","; done
      echo "  },"
      echo "}"
    } >"$out"
    ;;
  *)
    # kitty / alacritty: gogh already writes their config files, so they persist.
    :
    ;;
esac
