#!/usr/bin/env bash

RESET="\033[0m"
BOLD="\033[1m"
# shellcheck disable=SC2034
CYAN="\033[1;36m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
DIM="\033[2m"

# Terminal values gogh accepts (the colorscheme function passes TERMINAL straight
# to gogh's apply-colors.sh). Mirror of that script's dispatch — keep in sync if
# gogh adds terminals. install.sh only ships config templates for the first three.
COLORSCHEME_TERMINALS="alacritty kitty wezterm konsole gnome-terminal mate-terminal \
xfce4-terminal tilix guake foot terminator mintty iTerm.app pantheon-terminal \
io.elementary.terminal kmscon linux termux"

# Returns 0 when $1 is a terminal gogh/colorscheme can theme. Matches gogh's
# prefix cases for gnome-terminal* and io.elementary.t* as well.
# Usage: is_colorscheme_terminal <name>
is_colorscheme_terminal() {
  local term="${1:-}"
  [[ -z "$term" ]] && return 1
  case "$term" in
    gnome-terminal*|io.elementary.t*) return 0 ;;
  esac
  case " ${COLORSCHEME_TERMINALS} " in
    *" ${term} "*) return 0 ;;
    *) return 1 ;;
  esac
}

# Returns 0 when an install.sh INSTALL_* option only works if ~/{.zshrc,.bashrc}
# sources rc.sh (aliases, shell functions, plugin init, etc.).
# Usage: needs_shell_rc_wrapper <OPTION_SUFFIX>
needs_shell_rc_wrapper() {
  case "$1" in
    ALIASES|AUTOSUGG|RBENV|NVM|FZF|GOGH) return 0 ;;
    *) return 1 ;;
  esac
}

# Returns 0 when an install.sh INSTALL_* option only wires into FZF via rc.sh
# (file listing, previews, or the colorscheme picker).
# Usage: needs_fzf_for_install <OPTION_SUFFIX>
needs_fzf_for_install() {
  case "$1" in
    RIPGREP|BAT|GOGH) return 0 ;;
    *) return 1 ;;
  esac
}

# Machine-local env, secrets, and install-managed exports (TERMINAL, fonts, …).
# Usage: local_sh_path
local_sh_path() {
  printf '%s/.local.sh\n' "$HOME"
}

# Migrate legacy paths to ~/.local.sh (repo shell/custom.sh, then ~/.custom.sh).
# Usage: migrate_local_sh <dotfiles_dir>
migrate_local_sh() {
  local dotfiles_dir="$1"
  local dest legacy_repo legacy_home
  dest="$(local_sh_path)"

  [ -f "$dest" ] && return 0

  legacy_repo="$dotfiles_dir/shell/custom.sh"
  if [ -f "$legacy_repo" ]; then
    cp "$legacy_repo" "$dest"
    rm -f "$legacy_repo"
    echo -e "  ${GREEN}✓${RESET}  Migrated ${DIM}shell/custom.sh${RESET} → ${DIM}~/.local.sh${RESET}"
    return 0
  fi

  legacy_home="${HOME}/.custom.sh"
  if [ -f "$legacy_home" ]; then
    cp "$legacy_home" "$dest"
    rm -f "$legacy_home"
    echo -e "  ${GREEN}✓${RESET}  Migrated ${DIM}~/.custom.sh${RESET} → ${DIM}~/.local.sh${RESET}"
  fi
}

# Installs a local ~/.zshrc or ~/.bashrc that sources rc.sh from this repo.
# Other tools can append their own lines below the managed block.
#
# Usage: install_shell_rc_wrapper <rc.sh> <dest>
install_shell_rc_wrapper() {
  local src="$1"
  local dest="$2"
  local tmp preserved header footer block inblock

  src="$(cd "$(dirname "$src")" && pwd)/$(basename "$src")"

  header="# $(basename "$dest") — local shell startup (managed by terminal-config)
# Generated by install.sh / update.sh — safe for other tools to append below."
  footer="# Other tools (nvm, conda, etc.) may append below this line."
  block="# terminal-config: begin
source \"$src\"
# terminal-config: end"

  if [ -f "$dest" ] && grep -qF '# terminal-config: begin' "$dest"; then
    tmp=$(mktemp)
    inblock=0
    while IFS= read -r line || [ -n "$line" ]; do
      if [ "$line" = "# terminal-config: begin" ]; then
        printf '%s\n' "# terminal-config: begin"
        printf 'source "%s"\n' "$src"
        printf '%s\n' "# terminal-config: end"
        inblock=1
        continue
      fi
      if [ "$inblock" = 1 ] && [ "$line" = "# terminal-config: end" ]; then
        inblock=0
        continue
      fi
      [ "$inblock" = 1 ] && continue
      printf '%s\n' "$line"
    done <"$dest" >"$tmp"
    mv "$tmp" "$dest"
    echo -e "  ${GREEN}✓${RESET}  $dest updated (terminal-config source refreshed)."
    return 0
  fi

  if [ -L "$dest" ]; then
    local link_target
    link_target="$(readlink "$dest")"
    [[ "$link_target" != /* ]] && link_target="$(cd "$(dirname "$dest")" && pwd)/$link_target"
    if [ "$link_target" = "$src" ]; then
      echo -e "  ${DIM}Converting $dest symlink → local wrapper.${RESET}"
    else
      echo -e "  ${YELLOW}⚠${RESET}  $dest points elsewhere — backing up as ${DIM}$dest.old${RESET}"
      mv "$dest" "$dest.old"
    fi
    [ -L "$dest" ] && rm "$dest"
  elif [ -f "$dest" ]; then
    echo -e "  ${YELLOW}⚠${RESET}  $dest already exists — backing up as ${DIM}$dest.old${RESET}"
    mv "$dest" "$dest.old"
    preserved=$(cat "${dest}.old")
  fi

  {
    printf '%s\n\n' "$header"
    printf '%s\n\n' "$block"
    printf '%s\n' "$footer"
    if [ -n "${preserved:-}" ]; then
      printf '\n%s\n' "$preserved"
    fi
  } >"$dest"
  echo -e "  ${GREEN}✓${RESET}  $dest installed (sources rc.sh; other tools may append below)."
}

if [ -z "${DOTFILES_DIR:-}" ]; then
  DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi

# shellcheck source=../shell/common/reload.sh disable=SC1091
source "$DOTFILES_DIR/shell/common/reload.sh"

# Remove a shell RC wrapper or symlink managed by this repo.
# Usage: uninstall_shell_rc_if_mine <dotfiles_dir> <dest>
uninstall_shell_rc_if_mine() {
  local dotfiles="$1"
  local dest="$2"

  if [ -L "$dest" ] && [[ "$(readlink "$dest")" == "$dotfiles"* ]]; then
    uninstall_symlink_if_mine "$dotfiles" "$dest"
    return
  fi

  if [ -f "$dest" ] && grep -qF '# terminal-config: begin' "$dest"; then
    cp "$dest" "${dest}.uninstall.old"
    rm "$dest"
    echo -e "  ${GREEN}✓${RESET}  Removed ${dest} (backup at ${dest}.uninstall.old)"
    if [ -f "${dest}.old" ]; then
      mv "${dest}.old" "$dest"
      echo -e "  ${GREEN}✓${RESET}  Restored pre-install config from ${dest}.old"
    fi
    return
  fi

  if [ -e "$dest" ]; then
    echo -e "  ${DIM}—${RESET}  ${dest} is not managed by terminal-config — skipping."
  else
    echo -e "  ${DIM}—${RESET}  ${dest} not found — skipping."
  fi
}

# Links $1 (source) to $2 (destination), idempotently:
#   • already correct symlink  → skips
#   • symlink to wrong target  → removes and relinks
#   • regular file/dir         → backs up then links
link_file() {
  local src="$1"
  local dest="$2"

  if [ -L "$dest" ]; then
    if [ "$(readlink "$dest")" = "$src" ]; then
      echo -e "  ${GREEN}✓${RESET}  $dest already linked — skipping."
      return
    else
      echo -e "  ${YELLOW}⚠${RESET}  $dest points elsewhere — relinking."
      rm "$dest"
    fi
  elif [ -e "$dest" ]; then
    echo -e "  ${YELLOW}⚠${RESET}  $dest already exists — backing up as ${DIM}$dest.old${RESET}"
    mv "$dest" "$dest.old"
  fi

  ln -s "$src" "$dest"
  echo -e "  ${GREEN}✓${RESET}  $dest linked."
}

# Strip config keys removed in Alacritty 0.13+ that `alacritty migrate` may leave behind.
# Usage: _sanitize_alacritty_toml <path>
_sanitize_alacritty_toml() {
  local toml="$1" tmp

  [[ -f "$toml" ]] || return 0
  tmp=$(mktemp)
  awk '
    function flush_general() {
      if (!in_general) return
      if (general_keep) {
        print "[general]"
        printf "%s", general_buf
      }
      in_general = 0
      general_keep = 0
      general_buf = ""
    }
    /^\[(mouse\.double_click|mouse\.triple_click|mouse\.hints|window\.dpi)\]/ { skip = 1; next }
    /^\[/ {
      skip = 0
      if ($0 == "[general]") {
        flush_general()
        in_general = 1
        next
      }
      flush_general()
    }
    in_general {
      if ($0 ~ /^[[:space:]]*live_config_reload[[:space:]]*=[[:space:]]*true[[:space:]]*$/) next
      if ($0 ~ /^[[:space:]]*working_directory[[:space:]]*=[[:space:]]*"None"[[:space:]]*$/) next
      general_keep = 1
      general_buf = general_buf $0 ORS
      next
    }
    skip { next }
    /^"window\.(dynamic_title|opacity)"[[:space:]]*=/ { next }
    /^[[:space:]]*(alt_send_esc|enable_experimental_conpty_backend|ref_test|use_thin_strokes)[[:space:]]*=/ { next }
    { print }
    END { flush_general() }
  ' "$toml" >"$tmp" && mv "$tmp" "$toml"
}

# Migrate deprecated alacritty.yml to alacritty.toml (Alacritty 0.13+).
# Renames the YAML to alacritty.yml.old once TOML exists so launch warnings stop.
# Usage: migrate_alacritty_yaml_config [font_family]
migrate_alacritty_yaml_config() {
  local font_family="${1:-}"
  local dotfiles dir yml toml

  dir="${HOME}/.config/alacritty"
  yml="${dir}/alacritty.yml"
  toml="${dir}/alacritty.toml"
  mkdir -p "$dir"

  if [[ -f "$yml" ]]; then
    if [[ ! -f "$toml" ]] && command -v alacritty &>/dev/null; then
      echo -e "  ${DIM}Migrating deprecated alacritty.yml to alacritty.toml…${RESET}"
      alacritty migrate --config-file "$yml"
    fi

    if [[ -f "$toml" && -f "$yml" ]]; then
      mv "$yml" "${yml}.old"
      echo -e "  ${GREEN}✓${RESET}  Renamed deprecated ${DIM}alacritty.yml${RESET} → ${DIM}alacritty.yml.old${RESET}"
    fi
  fi

  if [[ -f "$toml" ]]; then
    _sanitize_alacritty_toml "$toml"

    if [[ -n "$font_family" ]] && grep -q '{{FONT_FAMILY}}' "$toml" 2>/dev/null; then
      dotfiles="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
      # shellcheck source=fonts.sh
      source "$dotfiles/lib/fonts.sh"
      substitute_font_placeholder "$toml" "$font_family"
    fi
  fi
}

# Copy a config from a repo template into the user's home or config directory
# (real file, not a symlink). Keeps personal edits out of the dotfiles repo.
#
# Legacy installs symlinked configs into this repo; on migrate we:
#   1. Back up the symlink target to <dest>.old (so nothing is lost)
#   2. Remove the symlink and write a real file at <dest>
#   3. Never touch an existing regular file at <dest> (already migrated)
#
# Usage: install_config_from_template <dotfiles_dir> <example_rel> <dest_path> [font_family]
install_config_from_template() {
  local dotfiles="$1"
  local example_rel="$2"
  local dest="$3"
  local font_family="${4:-}"
  local example="$dotfiles/$example_rel"
  local legacy_src

  [ -f "$example" ] || return 1
  mkdir -p "$(dirname "$dest")"

  _apply_font_if_needed() {
    if [[ -n "$font_family" ]] && [[ -f "$dest" ]]; then
      # shellcheck source=fonts.sh
      source "$dotfiles/lib/fonts.sh"
      substitute_font_placeholder "$dest" "$font_family"
    fi
  }

  if [ -f "$dest" ] && [ ! -L "$dest" ]; then
    if grep -q '{{FONT_FAMILY}}' "$dest" 2>/dev/null; then
      _apply_font_if_needed
      echo -e "  ${GREEN}✓${RESET}  $dest already exists — applied missing font substitution."
    else
      echo -e "  ${GREEN}✓${RESET}  $dest already exists (local file) — skipping."
    fi
    return 0
  fi

  if [ -L "$dest" ] && [[ "$(readlink "$dest")" == "$dotfiles"* ]]; then
    legacy_src="$(readlink "$dest")"
    [[ "$legacy_src" != /* ]] && legacy_src="$(dirname "$dest")/$legacy_src"

    if [ -f "$legacy_src" ]; then
      cp "$legacy_src" "${dest}.old"
      echo -e "  ${GREEN}✓${RESET}  Backed up previous config to ${DIM}${dest}.old${RESET}"
      rm "$dest"
      cp "$legacy_src" "$dest"
    else
      echo -e "  ${YELLOW}⚠${RESET}  Symlink target missing (${legacy_src}) — using template."
      rm "$dest"
      cp "$example" "$dest"
      _apply_font_if_needed
    fi
    echo -e "  ${GREEN}✓${RESET}  Replaced dotfiles symlink with local copy at $dest"
    return 0
  fi

  if [ ! -e "$dest" ]; then
    cp "$example" "$dest"
    _apply_font_if_needed
    echo -e "  ${GREEN}✓${RESET}  Created $dest from template."
    return 0
  fi

  echo -e "  ${YELLOW}⚠${RESET}  $dest exists and is not a dotfiles symlink — skipping."
  return 0
}

# Remove a legacy config file left in the repo after migrating to a local copy.
# Backs up the repo file to <path>.old before deleting. Usage:
#   remove_legacy_repo_copy <repo_file> <local_dest>
remove_legacy_repo_copy() {
  local repo_file="$1"
  local dest="$2"

  [ -f "$repo_file" ] || return 0
  [ -f "$dest" ] && [ ! -L "$dest" ] || return 0

  cp "$repo_file" "${repo_file}.old"
  rm -f "$repo_file"
  echo -e "  ${GREEN}✓${RESET}  Removed legacy repo copy ${repo_file} (backed up to ${repo_file}.old)."
}

# Returns 0 (true) when running inside WSL (Windows Subsystem for Linux).
is_wsl() {
  [ -n "${WSL_DISTRO_NAME:-}" ] && return 0
  grep -qi microsoft /proc/version 2>/dev/null
}

# Windows username for /mnt/c/Users/<name> (WSL only).
wsl_windows_user() {
  command -v cmd.exe >/dev/null 2>&1 || return 1
  cmd.exe /c 'echo %USERNAME%' 2>/dev/null | tr -d '\r\n'
}

# Mounted Windows user profile, e.g. /mnt/c/Users/alexesba (WSL only).
wsl_windows_home() {
  local user="${1:-}"
  [ -d /mnt/c/Users ] || return 1
  if [ -z "$user" ]; then
    user="$(wsl_windows_user 2>/dev/null || true)"
  fi
  if [ -n "$user" ] && [ -d "/mnt/c/Users/$user" ]; then
    printf '/mnt/c/Users/%s\n' "$user"
    return 0
  fi
  return 1
}

# True when Kitty or Linux Alacritty runs inside WSL (needs fonts in ~/.local/share/fonts).
wsl_linux_gui_terminal_detected_p() {
  is_wsl || return 1
  wsl_kitty_detected_p || wsl_linux_alacritty_p
}

# Directory where WezTerm reads wezterm.lua / colors.lua.
# Override with WEZTERM_CONFIG_DIR in ~/.local.sh.
# On WSL, defaults to the Windows profile when not set.
wezterm_config_dir() {
  if [ -n "${WEZTERM_CONFIG_DIR:-}" ]; then
    printf '%s\n' "$WEZTERM_CONFIG_DIR"
    return 0
  fi

  if is_wsl; then
    local win_home
    win_home="$(wsl_windows_home 2>/dev/null || true)"
    if [ -n "$win_home" ]; then
      if [ -f "$win_home/.config/wezterm/wezterm.lua" ] || [ -f "$win_home/.config/wezterm/colors.lua" ]; then
        printf '%s/.config/wezterm\n' "$win_home"
        return 0
      fi
      if [ -f "$win_home/.wezterm.lua" ]; then
        printf '%s\n' "$win_home"
        return 0
      fi
      printf '%s/.config/wezterm\n' "$win_home"
      return 0
    fi
  fi

  printf '%s/.config/wezterm\n' "$HOME"
}

# True when this shell is hosted inside WezTerm (including WSL panes).
hosting_wezterm_p() {
  [ -n "${WEZTERM_PANE:-}" ] || [ -n "${WEZTERM_EXECUTABLE:-}" ] || [ "${TERM_PROGRAM:-}" = WezTerm ]
}

# True when this shell is hosted inside Kitty.
hosting_kitty_p() {
  [ -n "${KITTY_WINDOW_ID:-}" ] || [ "${TERM_PROGRAM:-}" = kitty ] || [ "${TERM:-}" = xterm-kitty ]
}

# True when this shell is hosted inside Alacritty.
hosting_alacritty_p() {
  [ -n "${ALACRITTY_SOCKET:-}" ] || [ -n "${ALACRITTY_LOG:-}" ] || [ "${TERM:-}" = alacritty ]
}

# Windows %APPDATA% (Roaming) as a WSL path, e.g. /mnt/c/Users/you/AppData/Roaming.
wsl_appdata_roaming() {
  local win_home
  win_home="$(wsl_windows_home 2>/dev/null || true)"
  [ -n "$win_home" ] && printf '%s/AppData/Roaming' "$win_home"
}

# Directory where Kitty reads kitty.conf / colors.conf.
# Override with KITTY_CONFIG_DIRECTORY in ~/.local.sh.
# Kitty has no native Windows build; on WSL use the Linux package and ~/.config/kitty.
kitty_config_dir() {
  if [ -n "${KITTY_CONFIG_DIRECTORY:-}" ]; then
    printf '%s\n' "$KITTY_CONFIG_DIRECTORY"
    return 0
  fi
  printf '%s/.config/kitty\n' "$HOME"
}

# Directory containing alacritty.toml (or .yml).
# On WSL: Linux package → ~/.config/alacritty; Windows .exe → %APPDATA%/alacritty.
# Override parent dir with ALACRITTY_XDG_CONFIG_HOME in ~/.local.sh.
alacritty_config_dir() {
  if [ -n "${ALACRITTY_XDG_CONFIG_HOME:-}" ]; then
    printf '%s/alacritty\n' "$ALACRITTY_XDG_CONFIG_HOME"
    return 0
  fi
  if is_wsl && wsl_linux_alacritty_p; then
    printf '%s/alacritty\n' "${XDG_CONFIG_HOME:-$HOME/.config}"
    return 0
  fi
  if is_wsl; then
    local roaming
    roaming="$(wsl_appdata_roaming 2>/dev/null || true)"
    if [ -n "$roaming" ] && wsl_windows_alacritty_p; then
      printf '%s/alacritty\n' "$roaming"
      return 0
    fi
  fi
  printf '%s/alacritty\n' "${XDG_CONFIG_HOME:-$HOME/.config}"
}

# XDG_CONFIG_HOME value for Gogh's apply-alacritty.py (parent of alacritty/).
alacritty_xdg_config_home() {
  if [ -n "${ALACRITTY_XDG_CONFIG_HOME:-}" ]; then
    printf '%s\n' "$ALACRITTY_XDG_CONFIG_HOME"
    return 0
  fi
  if is_wsl && wsl_linux_alacritty_p; then
    printf '%s\n' "${XDG_CONFIG_HOME:-$HOME/.config}"
    return 0
  fi
  if is_wsl; then
    local roaming
    roaming="$(wsl_appdata_roaming 2>/dev/null || true)"
    if [ -n "$roaming" ] && wsl_windows_alacritty_p; then
      printf '%s\n' "$roaming"
      return 0
    fi
  fi
  printf '%s\n' "${XDG_CONFIG_HOME:-$HOME/.config}"
}

# True when a WezTerm config or generated colors.lua exists (Linux or WSL Windows mount).
wezterm_config_present_p() {
  local dir
  dir="$(wezterm_config_dir)"
  [ -f "$dir/wezterm.lua" ] || [ -f "$dir/.wezterm.lua" ] || [ -f "$dir/colors.lua" ]
}

kitty_config_present_p() {
  local dir
  dir="$(kitty_config_dir)"
  [ -f "$dir/kitty.conf" ] || [ -f "$dir/colors.conf" ]
}

alacritty_config_present_p() {
  local dir
  dir="$(alacritty_config_dir)"
  [ -f "$dir/alacritty.toml" ] || [ -f "$dir/alacritty.yml" ]
}

# Config file path for alacritty|kitty|wezterm (for display and existence checks).
terminal_emulator_config_path() {
  case "$1" in
    alacritty)
      local dir
      dir="$(alacritty_config_dir)"
      if [ -f "$dir/alacritty.toml" ]; then
        printf '%s/alacritty.toml\n' "$dir"
      elif [ -f "$dir/alacritty.yml" ]; then
        printf '%s/alacritty.yml\n' "$dir"
      else
        printf '%s/alacritty.toml\n' "$dir"
      fi
      ;;
    kitty)     printf '%s/kitty.conf\n' "$(kitty_config_dir)" ;;
    wezterm)
      local dir
      dir="$(wezterm_config_dir)"
      if [ -f "$dir/.wezterm.lua" ]; then
        printf '%s/.wezterm.lua\n' "$dir"
      else
        printf '%s/wezterm.lua\n' "$dir"
      fi
      ;;
    *) return 1 ;;
  esac
}

# True when emulator $1 is available for use-terminal / colorscheme.
terminal_emulator_installed_p() {
  case "$1" in
    wezterm)
      command -v wezterm >/dev/null 2>&1 && return 0
      hosting_wezterm_p && return 0
      wezterm_config_present_p && return 0
      is_wsl && return 0
      return 1
      ;;
    kitty)
      command -v kitty >/dev/null 2>&1 && return 0
      hosting_kitty_p && return 0
      is_wsl && kitty_config_present_p && return 0
      return 1
      ;;
    alacritty)
      command -v alacritty >/dev/null 2>&1 && return 0
      hosting_alacritty_p && return 0
      is_wsl && wsl_alacritty_detected_p && return 0
      return 1
      ;;
    *) return 1 ;;
  esac
}

# True when WezTerm appears to be installed on Windows (WSL install-time detection).
wsl_wezterm_detected_p() {
  local win_home exe

  is_wsl || return 1
  hosting_wezterm_p && return 0
  wezterm_config_present_p && return 0

  win_home="$(wsl_windows_home 2>/dev/null || true)"
  [ -n "$win_home" ] || return 1

  for exe in \
    "/mnt/c/Program Files/WezTerm/wezterm.exe" \
    "/mnt/c/Program Files/WezTerm/wezterm-gui.exe" \
    "$win_home/AppData/Local/Programs/WezTerm/wezterm.exe"; do
    [ -f "$exe" ] && return 0
  done
  return 1
}

# True when Linux Kitty is available in WSL (apt install kitty; no Windows build).
wsl_kitty_detected_p() {
  is_wsl || return 1
  command -v kitty >/dev/null 2>&1 && return 0
  hosting_kitty_p && return 0
  kitty_config_present_p && return 0
  return 1
}

# True when Alacritty runs as a Linux package in WSL (apt, etc.).
wsl_linux_alacritty_p() {
  is_wsl || return 1
  command -v alacritty >/dev/null 2>&1 && return 0
  hosting_alacritty_p && return 0
  if [ -f "$HOME/.config/alacritty/alacritty.toml" ] \
    || [ -f "$HOME/.config/alacritty/alacritty.yml" ]; then
    return 0
  fi
  return 1
}

# True when the Windows Alacritty .exe (or its Roaming config) is present.
wsl_windows_alacritty_p() {
  local win_home roaming exe

  is_wsl || return 1
  win_home="$(wsl_windows_home 2>/dev/null || true)"
  if [ -n "$win_home" ]; then
    for exe in \
      "/mnt/c/Program Files/Alacritty/alacritty.exe" \
      "$win_home/AppData/Local/Programs/Alacritty/alacritty.exe"; do
      [ -f "$exe" ] && return 0
    done
  fi
  roaming="$(wsl_appdata_roaming 2>/dev/null || true)"
  if [ -n "$roaming" ] && {
    [ -f "$roaming/alacritty/alacritty.toml" ] || [ -f "$roaming/alacritty/alacritty.yml" ]
  }; then
    return 0
  fi
  return 1
}

# True when Alacritty is available in WSL (Linux package and/or Windows install).
wsl_alacritty_detected_p() {
  wsl_linux_alacritty_p || wsl_windows_alacritty_p
}

# True when any supported GUI terminal is detected on Windows (WSL).
wsl_terminal_detected_p() {
  wsl_wezterm_detected_p || wsl_kitty_detected_p || wsl_alacritty_detected_p
}

# Export env vars Gogh needs to write kitty/alacritty configs on WSL.
gogh_export_terminal_env() {
  local _dir
  case "$1" in
    kitty)
      _dir="$(kitty_config_dir)"
      export KITTY_CONFIG_DIRECTORY="$_dir"
      ;;
    alacritty)
      _dir="$(alacritty_xdg_config_home)"
      export XDG_CONFIG_HOME="$_dir"
      ;;
  esac
}

# Write TERMINAL and Windows config paths to ~/.local.sh for detected WSL terminals.
configure_wsl_terminals_local_sh() {
  local file="$1" default_term=""

  is_wsl || return 0
  wsl_terminal_detected_p || return 0

  if wsl_kitty_detected_p; then
    set_env_var "$file" KITTY_CONFIG_DIRECTORY "$(kitty_config_dir)"
    default_term="${default_term:-kitty}"
  fi
  if wsl_alacritty_detected_p; then
    if wsl_windows_alacritty_p && ! wsl_linux_alacritty_p; then
      set_env_var "$file" ALACRITTY_XDG_CONFIG_HOME "$(alacritty_xdg_config_home)"
    fi
    default_term="${default_term:-alacritty}"
  fi
  if wsl_wezterm_detected_p; then
    set_env_var "$file" WEZTERM_CONFIG_DIR "$(unset WEZTERM_CONFIG_DIR; wezterm_config_dir)"
    default_term="${default_term:-wezterm}"
  fi

  if hosting_kitty_p; then
    default_term="kitty"
  elif hosting_alacritty_p; then
    default_term="alacritty"
  elif hosting_wezterm_p; then
    default_term="wezterm"
  fi

  [ -n "$default_term" ] && set_env_var "$file" TERMINAL "$default_term"
}

# Back-compat alias.
configure_wsl_wezterm_local_sh() {
  configure_wsl_terminals_local_sh "$@"
}

# Copy terminal templates when missing (WSL: Windows path for wezterm; Linux home for kitty/alacritty).
# Usage: install_wsl_terminal_configs <dotfiles_dir> [font_id]
install_wsl_terminal_configs() {
  local dotfiles="$1" font_id="${2:-caskaydia}"

  is_wsl || return 0

  if wsl_wezterm_detected_p; then
    install_wsl_wezterm_config "$dotfiles" \
      "$(nerd_font_family_for_terminal "$font_id" wezterm)"
  fi
  if wsl_kitty_detected_p; then
    install_wsl_kitty_config "$dotfiles" \
      "$(nerd_font_family_for_terminal "$font_id" kitty)"
  fi
  if wsl_alacritty_detected_p; then
    migrate_alacritty_yaml_config "$(nerd_font_family_for_terminal "$font_id" alacritty)"
    install_wsl_alacritty_config "$dotfiles" \
      "$(nerd_font_family_for_terminal "$font_id" alacritty)"
  fi
}

install_wsl_kitty_config() {
  local dotfiles="$1" font_family="$2" dir dest

  dir="$(kitty_config_dir)"
  dest="$dir/kitty.conf"
  if [ -f "$dest" ]; then
    echo -e "  ${GREEN}✓${RESET}  Kitty config already exists — skipping template copy."
    return 0
  fi
  mkdir -p "$dir"
  install_config_from_template "$dotfiles" \
    "terminal-emulators/kitty.conf.example" \
    "$dest" \
    "$font_family"
}

install_wsl_alacritty_config() {
  local dotfiles="$1" font_family="$2" dir dest roaming

  roaming="$(wsl_appdata_roaming 2>/dev/null || true)"
  dir="$(alacritty_config_dir)"
  dest="$dir/alacritty.toml"
  if [ -f "$dest" ] || { [ -n "$roaming" ] && [ -f "$roaming/alacritty/alacritty.yml" ]; }; then
    echo -e "  ${GREEN}✓${RESET}  Alacritty config already exists — skipping template copy."
    return 0
  fi
  mkdir -p "$dir"
  install_config_from_template "$dotfiles" \
    "terminal-emulators/alacritty.toml.example" \
    "$dest" \
    "$font_family"
}

install_wsl_wezterm_config() {
  local dotfiles="$1" font_family="$2" dir dest win_home

  is_wsl || return 0
  wsl_wezterm_detected_p || return 0

  dir="$(unset WEZTERM_CONFIG_DIR; wezterm_config_dir)"
  win_home="$(wsl_windows_home 2>/dev/null || true)"
  if [ -f "$dir/wezterm.lua" ] || [ -f "$dir/.wezterm.lua" ]; then
    echo -e "  ${GREEN}✓${RESET}  WezTerm config already exists — skipping template copy."
    return 0
  fi
  if [ -n "$win_home" ] && [ -f "$win_home/.wezterm.lua" ]; then
    echo -e "  ${GREEN}✓${RESET}  WezTerm config already exists at ${win_home}/.wezterm.lua — skipping."
    return 0
  fi

  mkdir -p "$dir"
  dest="$dir/wezterm.lua"
  install_config_from_template "$dotfiles" \
    "terminal-emulators/wezterm.lua.example" \
    "$dest" \
    "$font_family"
}

# Sets or updates an `export VAR="value"` line in a target file, idempotently.
# Replaces an existing export of the same VAR — including a commented-out
# placeholder like `# export VAR=...` left by the template — otherwise appends.
# Usage: set_env_var <file> <VAR> <value>
set_env_var() {
  local file="$1" var="$2" value="$3" line match
  line="export ${var}=\"${value}\""
  match="^[[:space:]]*#?[[:space:]]*export[[:space:]]+${var}="
  [ -f "$file" ] || touch "$file"
  if grep -qE "$match" "$file"; then
    # -i.bak keeps this portable across BSD (macOS) and GNU sed; | avoids path clashes
    sed -i.bak -E "s|${match}.*|${line}|" "$file" && rm -f "$file.bak"
    echo -e "  ${GREEN}✓${RESET}  ${var} set in $(basename "$file") → ${value}"
  else
    printf '%s\n' "$line" >> "$file"
    echo -e "  ${GREEN}✓${RESET}  ${var} added to $(basename "$file") → ${value}"
  fi
}

# Returns 0 (proceed) when the user confirms, or when CONFIRM_INTERACTIVE is not
# set (non-interactive mode assumes yes). Set CONFIRM_INTERACTIVE=true to prompt.
# Usage: confirm_yes "prompt text"
confirm_yes() {
  local prompt="$1"
  if [[ "${CONFIRM_INTERACTIVE:-false}" == true ]]; then
    ask_yn "$prompt"
    [[ $REPLY =~ ^[Yy]$ ]]
  else
    return 0
  fi
}

# Remove a symlink into dotfiles_dir and restore a pre-install ${dest}.old if present.
# Usage: uninstall_symlink_if_mine <dotfiles_dir> <dest>
uninstall_symlink_if_mine() {
  local dotfiles="$1"
  local dest="$2"

  if [ -L "$dest" ] && [[ "$(readlink "$dest")" == "$dotfiles"* ]]; then
    rm "$dest"
    echo -e "  ${GREEN}✓${RESET}  Removed symlink ${dest}"
    if [ -f "${dest}.old" ]; then
      mv "${dest}.old" "$dest"
      echo -e "  ${GREEN}✓${RESET}  Restored pre-install config from ${dest}.old"
    fi
    return 0
  fi

  if [ -e "$dest" ]; then
    echo -e "  ${DIM}—${RESET}  ${dest} is not a dotfiles symlink — skipping."
  else
    echo -e "  ${DIM}—${RESET}  ${dest} not found — skipping."
  fi
}

# Remove a copied (or legacy symlinked) config file, backing up to <dest>.uninstall.old.
# Usage: uninstall_copied_config <dotfiles_dir> <dest>
uninstall_copied_config() {
  local dotfiles="$1"
  local dest="$2"
  local legacy_src

  if [ -L "$dest" ] && [[ "$(readlink "$dest")" == "$dotfiles"* ]]; then
    legacy_src="$(readlink "$dest")"
    [[ "$legacy_src" != /* ]] && legacy_src="$(dirname "$dest")/$legacy_src"
    if [ -f "$legacy_src" ]; then
      cp "$legacy_src" "${dest}.uninstall.old"
    fi
    rm "$dest"
    echo -e "  ${GREEN}✓${RESET}  Removed symlink ${dest} (backup at ${dest}.uninstall.old)"
    return 0
  fi

  if [ -f "$dest" ]; then
    cp "$dest" "${dest}.uninstall.old"
    rm "$dest"
    echo -e "  ${GREEN}✓${RESET}  Removed ${dest} (backup at ${dest}.uninstall.old)"
    return 0
  fi

  echo -e "  ${DIM}—${RESET}  ${dest} not found — skipping."
}

# Prompts yes/no and loops until the user enters y or n (case-insensitive).
# Usage: ask_yn "prompt text"; result in $REPLY
ask_yn() {
  local prompt="$1"
  while true; do
    read -p "   ${prompt} $(printf '\033[2m')(y/n)$(printf '\033[0m') " -n 1 -r; echo
    case "$REPLY" in
      [Yy]|[Nn]) return ;;
      *) echo -e "  ${YELLOW}⚠${RESET}  Please enter ${BOLD}y${RESET} or ${BOLD}n${RESET}." ;;
    esac
  done
}

# Prompts a numbered choice and loops until a valid number is entered.
# Optional third argument is the default when the user presses Enter.
# Usage: ask_choice "prompt text" <max> [default]; result in $REPLY
ask_choice() {
  local prompt="$1"
  local max="$2"
  local default="${3:-}"
  local hint="[1-${max}]"
  while true; do
    if [[ -n "$default" ]]; then
      hint="[1-${max}, default ${default}]"
    fi
    read -p "   ${prompt} $(printf '\033[2m')${hint}$(printf '\033[0m'): " -n 1 -r; echo
    if [[ -z "$REPLY" && -n "$default" ]]; then
      REPLY="$default"
    fi
    if [[ "$REPLY" =~ ^[1-9]$ ]] && (( REPLY >= 1 && REPLY <= max )); then
      return
    fi
    echo -e "  ${YELLOW}⚠${RESET}  Please enter a number between ${BOLD}1${RESET} and ${BOLD}${max}${RESET}."
  done
}
